name: 'PMD Analyzer Action'
description: 'Annotates violations from PMD analyzer'
inputs:
  pmd-version:
    description: 'PMD Version'
    required: true
    default: '6.31.0'
  source-path:
    description: 'Source Path'
    required: true
  rule-path:
    description: 'Ruleset file'
    required: true
  should-throw-error:
    description: 'Set to true if you want it to fail on PMD warnings. Default is false.'
    required: false
    default: false
outputs:
  no-of-violations:
    description: "No of violations"
    value: ${{ steps.parse-output.outputs.no-of-violations }}
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/ExecutePmd.sh ${{ inputs.pmd-version }} ${{ inputs.source-path }} ${{ inputs.rule-path }}
      shell: bash
    - id: parse-output
      run: python3 ${{ github.action_path}}/parse_output.py ${{ inputs.should-throw-error }}
      shell: bash
branding:
  icon: 'alert-octagon'
  color: 'orange'